//     // "@react-navigation/stack": "^6.4.1",
    // "@react-native-firebase/app": "^20.5.0",
    // "@azure/cognitiveservices-computervision": "^8.2.0",
    // "@azure/core-auth": "^1.8.0",
    // "expo-linking": "~6.3.1",
    // "expo-splash-screen": "~0.27.5",
    // "expo-status-bar": "~1.12.1",
    // "expo-web-browser": "~13.0.3",
    // "react-native-safe-area-context": "^4.10.5",
    // "react-native-screens": "^3.31.1",
